##
## EPITECH PROJECT, 2018
## Makefile
## File description:
## push_swap
##

all:
	$(MAKE) -C tournament/

clean:
	$(MAKE) clean -C tournament/

fclean:	clean
	$(MAKE) fclean -C tournament/

re:     fclean all

.PHONY: all clean fclean re
